<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Funtions\" />
    <Folder Include="Migrations\" />
    <Folder Include="Setup\" />
    <Folder Include="StoredProcedures\Auth\" />
    <Folder Include="StoredProcedures\Chat\" />
    <Folder Include="StoredProcedures\Test\" />
    <Folder Include="Views\" />
    <Folder Include="Tables\" />
  </ItemGroup>

</Project>
